/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SneakersRouteImport } from './routes/sneakers'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OrderGoodsRouteImport } from './routes/order-goods'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClothingRouteImport } from './routes/clothing'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SneakersRoute = SneakersRouteImport.update({
  id: '/sneakers',
  path: '/sneakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderGoodsRoute = OrderGoodsRouteImport.update({
  id: '/order-goods',
  path: '/order-goods',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClothingRoute = ClothingRouteImport.update({
  id: '/clothing',
  path: '/clothing',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/clothing': typeof ClothingRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/order-goods': typeof OrderGoodsRoute
  '/shop': typeof ShopRoute
  '/sneakers': typeof SneakersRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/clothing': typeof ClothingRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/order-goods': typeof OrderGoodsRoute
  '/shop': typeof ShopRoute
  '/sneakers': typeof SneakersRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/clothing': typeof ClothingRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/order-goods': typeof OrderGoodsRoute
  '/shop': typeof ShopRoute
  '/sneakers': typeof SneakersRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessories'
    | '/brands'
    | '/cart'
    | '/clothing'
    | '/contact'
    | '/lookbook'
    | '/order-goods'
    | '/shop'
    | '/sneakers'
    | '/wishlist'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessories'
    | '/brands'
    | '/cart'
    | '/clothing'
    | '/contact'
    | '/lookbook'
    | '/order-goods'
    | '/shop'
    | '/sneakers'
    | '/wishlist'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessories'
    | '/brands'
    | '/cart'
    | '/clothing'
    | '/contact'
    | '/lookbook'
    | '/order-goods'
    | '/shop'
    | '/sneakers'
    | '/wishlist'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRoute
  BrandsRoute: typeof BrandsRoute
  CartRoute: typeof CartRoute
  ClothingRoute: typeof ClothingRoute
  ContactRoute: typeof ContactRoute
  LookbookRoute: typeof LookbookRoute
  OrderGoodsRoute: typeof OrderGoodsRoute
  ShopRoute: typeof ShopRoute
  SneakersRoute: typeof SneakersRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sneakers': {
      id: '/sneakers'
      path: '/sneakers'
      fullPath: '/sneakers'
      preLoaderRoute: typeof SneakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-goods': {
      id: '/order-goods'
      path: '/order-goods'
      fullPath: '/order-goods'
      preLoaderRoute: typeof OrderGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clothing': {
      id: '/clothing'
      path: '/clothing'
      fullPath: '/clothing'
      preLoaderRoute: typeof ClothingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRoute,
  BrandsRoute: BrandsRoute,
  CartRoute: CartRoute,
  ClothingRoute: ClothingRoute,
  ContactRoute: ContactRoute,
  LookbookRoute: LookbookRoute,
  OrderGoodsRoute: OrderGoodsRoute,
  ShopRoute: ShopRoute,
  SneakersRoute: SneakersRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
